---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-serviceaccount-otel-collector.yaml
- 02-configmap-otel-collector.yaml
- 03-clusterrole-otel-collector.yaml
- 04-clusterrolebinding-otel-collector.yaml
- 05-service-otel-collector.yaml
- 06-deployment-otel-collector.yaml
